name: update-activity
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  activity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "chore: update activity feed"
          MAX_LINES: 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
